"""
Django settings for xy_neo4j project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or 'django-insecure-dev-key'

DJANGO_DB_PATH = Path(os.getenv('DJANGO_DB_PATH', str(BASE_DIR / 'outputs' / 'django.db')))
DJANGO_DB_PATH.parent.mkdir(parents=True, exist_ok=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,web').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myneo4j',
    'accounts',
    'mapping'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xy_neo4j.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xy_neo4j.wsgi.application'
ASGI_APPLICATION = 'xy_neo4j.asgi.application'

REDIS_URL = os.getenv('REDIS_URL', '').strip()
# Channels is retained for session/auth middleware; map progress now uses the
# dedicated Redis Streams or in-memory SSE broker rather than channel groups.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(DJANGO_DB_PATH),
    },
    'map_states': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'outputs' / 'states' / 'map_states.db',
    }
}

# 数据库路由器 - 将特定模型路由到不同的数据库
DATABASE_ROUTERS = ['mapping.routers.MapStatesRouter']


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STATIC_DIRS = (
    os.path.join(BASE_DIR, 'static')
)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

DATAS_DIR = os.path.join(BASE_DIR, "datas")

# 生成的地图文件存储目录（与 static 同级）
GENERATED_MAPS_DIR = os.path.join(BASE_DIR, "generated_maps")

X_FRAME_OPTIONS = 'SAMEORIGIN'
ZHIPUAI_API_KEY = os.getenv('ZHIPUAI_API_KEY', '')

SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
# 禁用 SimpleUI 菜单缓存，确保菜单实时更新
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
# 清除旧的模型缓存
import time
# SimpleUI 配置
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['MAPPING', '用户管理'],
    'dynamic': True,  # 动态菜单
    'menus': [
        {
            'name': 'MAPPING',
            'icon': 'fas fa-map',
            'models': [
                {
                    'name': '地图制作请求',
                    'icon': 'fas fa-map-marked-alt',
                    'url': '/admin/mapping/maprequest/'
                },
                {
                    'name': 'Django 主数据库',
                    'icon': 'fas fa-database',
                    'url': '/admin/mapping/maindatabase/'
                },
                {
                    'name': '地图状态数据库',
                    'icon': 'fas fa-database',
                    'url': '/admin/mapping/mapstatesdatabase/'
                },
            ]
        },
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户管理',
                    'icon': 'fas fa-user',
                    'url': '/admin/accounts/userprofile/'
                },
            ]
        }
    ]
}

AUTH_USER_MODEL = 'accounts.UserProfile'
LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_URL = '/accounts/logout'

from .question_classifier import *
from .question_parser import *
from .answer_search import *
from .get_zhipu_response import *
from .ai_deepseek import *

CLASSIFIER = QuestionClassifier()
PARSER = QuestionPaser()
SEACHER = AnswerSearcher()
ZHIPU = GetZhipuResponse()
DEEPSEEK = GetDeepseek()
