import re

from playwright.sync_api import sync_playwright


with sync_playwright() as p:
    browser = p.chromium.launch(headless=True, executable_path=r"C:\Program Files\Google\Chrome\Application\chrome.exe")
    api = p.request.new_context()
    login_url = "http://127.0.0.1:8001/accounts/login"
    login_page = api.get(login_url)
    csrf = re.search(r'name="csrfmiddlewaretoken"[^>]+value="([^"]+)', login_page.text()).group(1)
    response = api.post(login_url, form={"csrfmiddlewaretoken": csrf, "username": "codex-test", "password": "CodexTest123!"}, max_redirects=0)
    print("login_status", response.status)
    context = browser.new_context(storage_state=api.storage_state())
    page = context.new_page()
    page.set_default_timeout(30000)
    page.on("console", lambda message: print("console", message.type, message.text))
    page.on("pageerror", lambda error: print("pageerror", error))
    page.on("requestfailed", lambda request: print("request_failed", request.url, request.failure))
    page.goto("http://127.0.0.1:8001/mapping/", wait_until="domcontentloaded")
    page.wait_for_timeout(4000)
    print("mapping_url", page.url)
    print("title", page.title())
    print("body_prefix", page.locator("body").inner_text()[:300])
    print("html_prefix", page.content()[:800])
    print("workbench_heading", page.get_by_text("智能制图工作台").count())
    print("map_canvas", page.locator(".map-canvas").count())
    print("chat_composer", page.locator(".composer textarea").count())
    if page.locator(".history-item").count():
        page.locator(".history-item").first.click()
        page.wait_for_timeout(1200)
        print("history_status", page.locator(".status-card strong").inner_text())
        print("result_card", page.locator("#result-card").count())
        print("stored_preview", page.locator(".stored-map-preview").count())
        print("file_actions", page.locator(".file-action").count())
        page.evaluate("window.scrollTo(0, 0)")
        page.locator(".map-stage").hover()
        print("page_scroll_before_map_wheel", page.evaluate("window.scrollY"))
        page.mouse.wheel(0, 500)
        page.wait_for_timeout(250)
        print("page_scroll_after_map_wheel", page.evaluate("window.scrollY"))
        print("inspector_scroll_after_map_wheel", page.locator(".inspector-scroll").evaluate("element => element.scrollTop"))
        viewport = page.locator(".stored-map-viewport")
        box = viewport.bounding_box()
        if box:
            page.mouse.move(box["x"] + 240, box["y"] + 220)
            page.mouse.down()
            page.mouse.move(box["x"] + 240, box["y"] + 280)
            page.mouse.up()
            print("preview_transform_after_drag", page.locator(".stored-map-viewport img").get_attribute("style"))
    page.screenshot(path="tests/manual_workbench.png", full_page=True)
    context.close()
    api.dispose()
    browser.close()
