# Generated by Django 3.2.7 on 2023-01-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='node的name')),
                ('leixing', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='类型的中文')),
            ],
            options={
                'verbose_name': '节点信息',
                'verbose_name_plural': '节点信息',
                'ordering': ['-id'],
            },
        ),
    ]
