# Generated by Django 3.2 on 2025-08-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='地图标题')),
                ('request_text', models.TextField(verbose_name='制图需求描述')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('map_config', models.JSONField(blank=True, default=dict, verbose_name='地图配置')),
                ('result_message', models.TextField(blank=True, verbose_name='处理结果消息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '地图制作请求',
                'verbose_name_plural': '地图制作请求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('map_extent', models.JSONField(blank=True, default=list, verbose_name='地图范围')),
                ('layers_info', models.JSONField(blank=True, default=list, verbose_name='图层信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_maps', to='mapping.maprequest', verbose_name='关联请求')),
            ],
            options={
                'verbose_name': '生成的地图',
                'verbose_name_plural': '生成的地图',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', '用户消息'), ('assistant', '助手回复'), ('system', '系统消息')], max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='mapping.maprequest', verbose_name='关联请求')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['created_at'],
            },
        ),
    ]
