# Generated by Django 3.2 on 2025-08-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', '用户消息'), ('assistant', '助手回复'), ('system', '系统消息'), ('log', '实时日志')], max_length=20, verbose_name='消息类型'),
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('debug', '调试')], default='info', max_length=20, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('step', models.CharField(blank=True, max_length=100, verbose_name='处理步骤')),
                ('progress', models.PositiveIntegerField(blank=True, null=True, verbose_name='进度百分比')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='mapping.maprequest', verbose_name='关联请求')),
            ],
            options={
                'verbose_name': '处理日志',
                'verbose_name_plural': '处理日志',
                'ordering': ['created_at'],
            },
        ),
    ]
