# Generated by Django 3.2.7 on 2025-10-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_add_version_and_session_fields'),
        ('mapping', '0002_auto_20250830_2232'),
    ]

    operations = [
    ]
