# Generated by Django 3.2.7 on 2025-10-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency("accounts.UserProfile"),
        ("mapping", "0003_merge_20251025_1710"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedmap",
            name="image_data",
            field=models.BinaryField(blank=True, null=True, verbose_name="图片数据"),
        ),
        migrations.AlterField(
            model_name="generatedmap",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_maps",
                to="mapping.maprequest",
                verbose_name="关联请求",
            ),
        ),
    ]
