# Generated by Django 3.2.7 on 2025-10-25 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0003_merge_20251025_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('session_name', models.CharField(blank=True, max_length=200, verbose_name='会话名称')),
                ('session_type', models.CharField(choices=[('traditional', '传统制图'), ('generalization', '路网综合')], default='traditional', max_length=20, verbose_name='会话类型')),
                ('current_version', models.PositiveIntegerField(default=1, verbose_name='当前版本')),
                ('total_maps', models.PositiveIntegerField(default=0, verbose_name='生成地图数量')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='总大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '地图会话',
                'verbose_name_plural': '地图会话',
                'ordering': ['-last_accessed'],
            },
        ),
        # 注释掉删除 file_path 的操作，保留文件路径存储方式
        # migrations.RemoveField(
        #     model_name='generatedmap',
        #     name='file_path',
        # ),
        migrations.AddField(
            model_name='generatedmap',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='图片数据'),
        ),
        migrations.AlterField(
            model_name='generatedmap',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_maps', to='mapping.maprequest', verbose_name='关联请求'),
        ),
        migrations.CreateModel(
            name='MapState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('map_id', models.CharField(max_length=100, verbose_name='地图ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='地图标题')),
                ('extent', models.JSONField(blank=True, null=True, verbose_name='地图范围')),
                ('crs', models.CharField(default='EPSG:4326', max_length=50, verbose_name='坐标系')),
                ('background_color', models.CharField(default='white', max_length=50, verbose_name='背景色')),
                ('figsize', models.JSONField(blank=True, null=True, verbose_name='图幅大小')),
                ('dpi', models.IntegerField(default=300, verbose_name='DPI')),
                ('maintain_data_aspect', models.BooleanField(default=False, verbose_name='保持数据纵横比')),
                ('fit_figsize_to_extent', models.BooleanField(default=False, verbose_name='自适应图幅')),
                ('auto_legend', models.BooleanField(default=True, verbose_name='自动图例')),
                ('auto_scalebar', models.BooleanField(default=True, verbose_name='自动比例尺')),
                ('auto_compass', models.BooleanField(default=True, verbose_name='自动指北针')),
                ('scalebar', models.JSONField(blank=True, null=True, verbose_name='比例尺配置')),
                ('compass', models.JSONField(blank=True, null=True, verbose_name='指北针配置')),
                ('is_generalization_task', models.BooleanField(default=False, verbose_name='是否路网综合任务')),
                ('generalization_result', models.JSONField(blank=True, null=True, verbose_name='路网综合结果')),
                ('parent_version', models.IntegerField(blank=True, null=True, verbose_name='父版本')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否当前版本')),
                ('image_data', models.BinaryField(blank=True, null=True, verbose_name='地图图片数据')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_states', to='mapping.mapsession', verbose_name='关联会话')),
            ],
            options={
                'verbose_name': '地图状态',
                'verbose_name_plural': '地图状态',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=100, verbose_name='图层ID')),
                ('name', models.CharField(max_length=200, verbose_name='图层名称')),
                ('data_source', models.TextField(verbose_name='数据源')),
                ('geometry_type', models.CharField(max_length=50, verbose_name='几何类型')),
                ('style', models.JSONField(blank=True, null=True, verbose_name='样式配置')),
                ('label_column', models.CharField(blank=True, max_length=100, verbose_name='标注字段')),
                ('label_style', models.JSONField(blank=True, null=True, verbose_name='标注样式')),
                ('visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('z_order', models.IntegerField(default=0, verbose_name='图层顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('map_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='mapping.mapstate', verbose_name='关联地图状态')),
            ],
            options={
                'verbose_name': '图层',
                'verbose_name_plural': '图层',
                'ordering': ['z_order'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='注记文本')),
                ('position', models.JSONField(blank=True, null=True, verbose_name='位置坐标')),
                ('style', models.JSONField(blank=True, null=True, verbose_name='样式配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('map_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='mapping.mapstate', verbose_name='关联地图状态')),
            ],
            options={
                'verbose_name': '注记',
                'verbose_name_plural': '注记',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mapstate',
            index=models.Index(fields=['session', 'version'], name='mapping_map_session_ac9a76_idx'),
        ),
        migrations.AddIndex(
            model_name='mapstate',
            index=models.Index(fields=['session', 'is_current'], name='mapping_map_session_04696c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapstate',
            unique_together={('session', 'version')},
        ),
    ]
