# Generated by Django 3.2.7 on 2025-10-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_add_version_and_session_fields'),
        ('mapping', '0003_merge_20251008_2207'),
    ]

    operations = [
    ]
