# Generated by Django 3.2.7 on 2025-10-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20251025_1710'),
        ('mapping', '0004_merge_20251025_1649'),
    ]

    operations = [
    ]
